# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_reduce.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map_reduce.proto\x12\nmap_reduce\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"3\n\nMapRequest\x12\x12\n\nsplit_path\x18\x01 \x01(\t\x12\x11\n\tmapper_id\x18\x02 \x01(\x05\"\x1e\n\x0bMapResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\x0eReducerRequest\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x12\n\nreducer_id\x18\x02 \x01(\x05\"!\n\x0eReduceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rPartitionData\x12\r\n\x05lines\x18\x01 \x03(\t2\x8b\x01\n\x06Mapper\x12\x36\n\x03Map\x12\x16.map_reduce.MapRequest\x1a\x17.map_reduce.MapResponse\x12I\n\x10GetPartitionData\x12\x1a.map_reduce.ReducerRequest\x1a\x19.map_reduce.PartitionData2K\n\x07Reducer\x12@\n\x06Reduce\x12\x1a.map_reduce.ReducerRequest\x1a\x1a.map_reduce.ReduceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=32
  _globals['_POINT']._serialized_end=61
  _globals['_MAPREQUEST']._serialized_start=63
  _globals['_MAPREQUEST']._serialized_end=114
  _globals['_MAPRESPONSE']._serialized_start=116
  _globals['_MAPRESPONSE']._serialized_end=146
  _globals['_REDUCERREQUEST']._serialized_start=148
  _globals['_REDUCERREQUEST']._serialized_end=203
  _globals['_REDUCERESPONSE']._serialized_start=205
  _globals['_REDUCERESPONSE']._serialized_end=238
  _globals['_PARTITIONDATA']._serialized_start=240
  _globals['_PARTITIONDATA']._serialized_end=270
  _globals['_MAPPER']._serialized_start=273
  _globals['_MAPPER']._serialized_end=412
  _globals['_REDUCER']._serialized_start=414
  _globals['_REDUCER']._serialized_end=489
# @@protoc_insertion_point(module_scope)
